stages:
  prepare:
    cmd: python -m src.ml.data
    deps:
      - src/ml/data.py
      - creditcard.csv
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet
      - data/processed/reference.parquet
      - data/processed/current.parquet
  train:
    cmd: python -m src.ml.train
    deps:
      - src/ml/train.py
      - configs/base.yaml
      - configs/training.yaml
      - data/processed/train.parquet
      - data/processed/test.parquet
    outs:
      - models/latest.joblib
  evaluate:
    cmd: python -m src.ml.evaluate
    deps:
      - src/ml/evaluate.py
      - models/latest.joblib
      - data/processed/test.parquet
